import { Router } from "express";
import { demoScenarioConfig } from "../config/demoScenario";
import { prisma } from "../lib/prisma";

export const setupRouter = Router();

setupRouter.get("/status", async (_request, response) => {
  const [counts, demoUser, activeDemoConfig] = await Promise.all([
    prisma.$transaction([
      prisma.user.count(),
      prisma.role.count(),
      prisma.permission.count(),
      prisma.userRole.count(),
      prisma.rolePermission.count(),
      prisma.company.count(),
      prisma.department.count(),
      prisma.sku.count(),
      prisma.customer.count(),
      prisma.supplier.count(),
      prisma.warehouse.count(),
      prisma.warehouseLocation.count(),
      prisma.vehicle.count(),
      prisma.driver.count(),
      prisma.demoConfig.count(),
      prisma.document.count(),
      prisma.contract.count(),
      prisma.contractItem.count(),
      prisma.batch.count(),
      prisma.qrItem.count(),
      prisma.stockMovement.count(),
      prisma.inventorySnapshot.count(),
      prisma.stocktakeOrder.count(),
      prisma.stocktakeItem.count(),
      prisma.purchaseOrder.count(),
      prisma.purchaseOrderItem.count(),
      prisma.shipment.count(),
      prisma.shipmentNode.count(),
      prisma.customsClearance.count(),
      prisma.preReceiveOrder.count(),
      prisma.inboundOrder.count(),
      prisma.outboundOrder.count(),
      prisma.salesOrder.count(),
      prisma.salesOrderItem.count(),
      prisma.deliveryOrder.count(),
      prisma.deliveryOrderItem.count(),
      prisma.payment.count(),
      prisma.receivable.count(),
      prisma.payable.count(),
      prisma.invoice.count(),
      prisma.costItem.count(),
      prisma.exchangeRate.count(),
      prisma.bankAccount.count(),
      prisma.settlement.count(),
      prisma.workOrder.count(),
      prisma.approval.count(),
      prisma.approvalStep.count(),
      prisma.notification.count(),
      prisma.auditLog.count(),
      prisma.aiLog.count(),
      prisma.reportSnapshot.count()
    ]),
    prisma.user.findUnique({
      where: { username: "demo-owner" },
      select: {
        id: true,
        username: true,
        displayName: true,
        email: true,
        phone: true,
        role: true,
        status: true,
        companyId: true,
        departmentId: true,
        createdAt: true
      }
    }),
    prisma.demoConfig.findFirst({
      where: { status: "ACTIVE" },
      orderBy: { updatedAt: "desc" },
      select: {
        id: true,
        scenarioName: true,
        origin: true,
        destinationWarehouse: true,
        customerName: true,
        supplierName: true,
        productName: true,
        totalQuantity: true,
        unit: true,
        plannedOutboundQuantity: true,
        amount: true,
        currency: true,
        customerId: true,
        supplierId: true,
        skuId: true,
        warehouseId: true,
        status: true,
        createdAt: true,
        updatedAt: true
      }
    })
  ]);

  const [
    users,
    roles,
    permissions,
    userRoles,
    rolePermissions,
    companies,
    departments,
    skus,
    customers,
    suppliers,
    warehouses,
    warehouseLocations,
    vehicles,
    drivers,
    demoConfigs,
    documents,
    contracts,
    contractItems,
    batches,
    qrItems,
    stockMovements,
    inventorySnapshots,
    stocktakeOrders,
    stocktakeItems,
    purchaseOrders,
    purchaseOrderItems,
    shipments,
    shipmentNodes,
    customsClearances,
    preReceiveOrders,
    inboundOrders,
    outboundOrders,
    salesOrders,
    salesOrderItems,
    deliveryOrders,
    deliveryOrderItems,
    payments,
    receivables,
    payables,
    invoices,
    costItems,
    exchangeRates,
    bankAccounts,
    settlements,
    workOrders,
    approvals,
    approvalSteps,
    notifications,
    auditLogs,
    aiLogs,
    reportSnapshots
  ] = counts;

  response.json({
    database: {
      status: "ok",
      provider: "sqlite",
      counts: {
        users,
        roles,
        permissions,
        userRoles,
        rolePermissions,
        companies,
        departments,
        skus,
        customers,
        suppliers,
        warehouses,
        warehouseLocations,
        vehicles,
        drivers,
        documents,
        contracts,
        contractItems,
        batches,
        qrItems,
        stockMovements,
        inventorySnapshots,
        stocktakeOrders,
        stocktakeItems,
        purchaseOrders,
        purchaseOrderItems,
        shipments,
        shipmentNodes,
        customsClearances,
        preReceiveOrders,
        inboundOrders,
        outboundOrders,
        salesOrders,
        salesOrderItems,
        deliveryOrders,
        deliveryOrderItems,
        payments,
        receivables,
        payables,
        invoices,
        costItems,
        exchangeRates,
        bankAccounts,
        settlements,
        workOrders,
        approvals,
        approvalSteps,
        notifications,
        auditLogs,
        aiLogs,
        reportSnapshots,
        demoConfigs
      }
    },
    demoUser,
    demoScenario: activeDemoConfig ?? {
      ...demoScenarioConfig,
      status: "ENV_FALLBACK"
    }
  });
});
